base_url = "https://lonnen.com"
build_search_index = false
compile_sass = true
default_language = "en"
theme = "terminimal"

[markdown]
highlight_code = true

[extra]
accent_color = "green"
background_color = "dark"
logo_text = " "
author = "Lonnen"
# og_image = "colocated_image.png"
# default_og_image = "static/ocean.jpg"

menu_items = [
    {name = "xor (blog)", url = "https://xor.lonnen.com/"},
    {name = "github", url = "https://github.com/lonnen"},
    {name = "bsky", url = "https://bsky.app/profile/lonnen.departmentoflastresort.com"}
]
